name: auto_orientation_plus
description: Set the device orientation programmatically for iOS and Android
version: 2.3.2
homepage: https://github.com/KhushalJangid/auto_orientation_plus
repository: https://github.com/KhushalJangid/auto_orientation_plus
issue_tracker: https://github.com/KhushalJangid/auto_orientation_plus/issues

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.khushaljangid.auto_orientation_plus
        pluginClass: AutoOrientationPlugin
      ios:
        pluginClass: AutoOrientationPlugin
